### ISSUE TITLE
Pie Chart Repetitive Press Error on Android

### ISSUE THREAD

**Issue by ChrisGatzo** [FormidableLabs/victory-native#152]
Hello,

I'm getting an exception on Android when pressing the slices of the pie chart repetitively in random order. The exception seems to be coming from the react native svg library and it reads:

`FATAL EXCEPTION: main
                                                              Process: com.test.helloworld, PID: 24771
                                                              java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                  at java.util.ArrayList.get(ArrayList.java:411)
                                                                  at com.facebook.react.uimanager.ReactShadowNode.getChildAt(ReactShadowNode.java:220)
                                                                  at com.horcrux.svg.GroupShadowNode.hitTest(GroupShadowNode.java:100)
                                                                  at com.horcrux.svg.GroupShadowNode.hitTest(GroupShadowNode.java:107)
                                                                  at com.horcrux.svg.SvgViewShadowNode.hitTest(SvgViewShadowNode.java:189)
                                                                  at com.horcrux.svg.SvgView.dispatchTouchEvent(SvgView.java:89)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2654)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                                  at android.view.View.dispatchPointerEvent(View.java:10243)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)`

Anybody else having this issue?

Thanks.

**Comment by stsiushkevich** [comment]
I have a such issue too
