### ISSUE TITLE
[Android] Victory Chart Native demo project fails with OutOfMemoryError

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/victory-native#34]
Running the [victory-chart-native demo project](https://github.com/FormidableLabs/victory-chart-native/tree/master/demo) on Genymotion virtual device (Google Nexus 5 - 6.0.0 - API 23, 4096MB base memory), the app crashes after a few seconds with an `OutOfMemoryError` (complete stack trace below).

The demo app generates a new data set every three seconds and re-renders all charts. Internally `react-native-svg` creates a new bitmap for each render, and the previous bitmaps do not get cleaned up before the new ones are generated, causing the app to increase the maximum heap growth limit.

The application heap size is [specific to each device model](http://stackoverflow.com/a/5352488/4333), and not proportional to the total memory available on the device. For the test device (Nexus 5) the heap growth limit is 192MB. As a workaround, we can increase the heap size to 512MB by specifying the following property in the application's AndroidManifest.xml:

```
    <application
      ... other properties
      android:largeHeap="true">
```

I propose to add this to the native-specific documentation.

Stack trace:
```
11-28 06:30:41.027 W/art     ( 2402): Throwing OutOfMemoryError "Failed to allocate a 3888012 byte allocation with 2691008 free bytes and 2MB until OOM"
11-28 06:30:41.028 E/AndroidRuntime( 2402): FATAL EXCEPTION: mqt_native_modules
11-28 06:30:41.028 E/AndroidRuntime( 2402): Process: com.demo, PID: 2402
11-28 06:30:41.028 E/AndroidRuntime( 2402): java.lang.OutOfMemoryError: Failed to allocate a 3888012 byte allocation with 2691008 free bytes and 2MB until OOM
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.graphics.Bitmap.nativeCreate(Native Method)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.horcrux.svg.RNSVGSvgViewShadowNode.drawOutput(RNSVGSvgViewShadowNode.java:69)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.horcrux.svg.RNSVGSvgViewShadowNode.onCollectExtraUpdates(RNSVGSvgViewShadowNode.java:58)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.ReactShadowNode.dispatchUpdates(ReactShadowNode.java:246)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:792)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:783)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:783)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:783)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:783)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:783)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:540)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:528)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:500)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.cxxbridge.NativeModuleRegistry$1.onBatchComplete(NativeModuleRegistry.java:72)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.cxxbridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:130)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.cxxbridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:129)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.os.Handler.handleCallback(Handler.java:739)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.os.Handler.dispatchMessage(Handler.java:95)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at android.os.Looper.loop(Looper.java:148)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
11-28 06:30:41.028 E/AndroidRuntime( 2402):     at java.lang.Thread.run(Thread.java:818)
```

**Comment by wk1017553772** [comment]
I have same problem in my Phone. The Demo programe can not run  directly !
