### ISSUE TITLE
@providesModule declaration with the same name across two different files.

### ISSUE THREAD

**Issue by hybrisCole** [FormidableLabs/victory-native#39]
Hello, 

I'm getting this when trying to `npm run start` on my RN.

RN Version: 0.33.1
Victory: 0.5.0

Regards,

```
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: String.prototype.es6
  Paths: /Users/albertocole/Desktop/4tius_dev/mobile/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String
.prototype.es6.js collides with /Users/albertocole/Desktop/4tius_dev/mobile/node_modules/victory-native/node_modules/react-native/pa
ckager/react-packager/src/Resolver/polyfills/String.prototype.es6.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/albertocole/Desktop/4tius_dev/mobile/node_modules/react-native/packager/react-packager/src/n
ode-haste/DependencyGraph/HasteMap.js:155:13)
    at module.getName.then.name (/Users/albertocole/Desktop/4tius_dev/mobile/node_modules/react-native/packager/react-packager/src/n
ode-haste/DependencyGraph/HasteMap.js:115:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by pranav-pandey** [comment]
Using 0.6.0 and getting the same error on Jenkins build

```
Failed to build DependencyGraph: @providesModule naming collision:
 Duplicate module name: ActionSheetIOS
 Paths: /Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/victory-native/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js collides with /Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
 Duplicate module name: ActionSheetIOS
 Paths: /Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/victory-native/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js collides with /Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js

This error is caused by a @providesModule declaration with the same name across two different files.
   at HasteMap._updateHasteMap (/Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
   at module.getName.then.name (/Users/Shared/Jenkins/Home/jobs/babylon-mobile-app_staging-frendz_ios/workspace/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:115:31)
```
